package reporting

import (
	"html/template"
	"io"
)

var reportTemplate = template.Must(
	template.New("report").Parse(`
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{.Assessment.Name}} - RedLab Report</title>
	<style>
		body {
			font-family: Arial, sans-serif;
			margin: 40px;
			color: #222;
			background: #f5f7fa;
		}

		.container {
			max-width: 1100px;
			margin: auto;
			background: white;
			padding: 32px;
			box-shadow: 0 2px 12px rgba(0,0,0,0.08);
		}

		h1 {
			margin-bottom: 4px;
		}

		.meta {
			color: #666;
			margin-bottom: 28px;
		}

		.finding {
			border: 1px solid #ddd;
			padding: 20px;
			margin-bottom: 18px;
		}

		.severity {
			font-weight: bold;
		}

		.technique {
			font-family: monospace;
		}

		.footer {
			margin-top: 40px;
			color: #777;
			font-size: 13px;
		}
	</style>
</head>

<body>
<div class="container">

	<h1>{{.Assessment.Name}}</h1>

	<div class="meta">
		<p><strong>Assessment ID:</strong> {{.Assessment.ID}}</p>
		<p><strong>Agent:</strong> {{.Assessment.AgentID}}</p>
		<p><strong>Status:</strong> {{.Assessment.Status}}</p>
		<p><strong>Created:</strong> {{.Assessment.CreatedAt}}</p>
		<p><strong>Generated:</strong> {{.GeneratedAt}}</p>
	</div>

	<h2>Description</h2>
	<p>{{.Assessment.Description}}</p>

	<h2>Findings</h2>

	{{if .Findings}}

		{{range .Findings}}
		<div class="finding">
			<h3>{{.Title}}</h3>

			<p>
				<strong>Severity:</strong>
				<span class="severity">{{.Severity}}</span>
			</p>

			<p>
				<strong>MITRE ATT&CK:</strong>
				<span class="technique">
					{{.TechniqueID}} - {{.TechniqueName}}
				</span>
			</p>

			<p>
				<strong>Description:</strong>
				{{.Description}}
			</p>

			<p>
				<strong>Recommendation:</strong>
				{{.Recommendation}}
			</p>
		</div>
		{{end}}

	{{else}}

		<p>No findings have been recorded for this assessment.</p>

	{{end}}

	<div class="footer">
		Generated by RedLab - Active Directory Offensive Security Assessment Platform
	</div>

</div>
</body>
</html>
`),
)

func RenderReport(
	writer io.Writer,
	report *Report,
) error {
	return reportTemplate.Execute(
		writer,
		report,
	)
}
