APP_NAME=RedLab
APP_VERSION=0.1.0
APP_ENV=development

SERVER_PORT=8080
SERVER_READ_TIMEOUT=10
SERVER_WRITE_TIMEOUT=10

DB_HOST=localhost
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=redlab
DB_SSLMODE=disable

JWT_SECRET=supersecret
JWT_EXPIRE=24

LDAP_HOST=192.168.56.10
LDAP_PORT=389
LDAP_BASE_DN=DC=redlab,DC=local
LDAP_BIND_DN=CN=Administrator,CN=Users,DC=redlab,DC=local
LDAP_PASSWORD=Password123!
LDAP_SSL=false

LOG_LEVEL=debug
LOG_DEVELOPMENT=true